### ISSUE TITLE
Easiest way to operate on array of integers

### ISSUE THREAD

**Issue by JC3** [wickedest/myers-diff#3]
Does anybody know what the easiest way to modify this is to get it to work on arrays of integers instead of characters in a string? 

Aside from kludging the input to be newline-separated integer strings and running it in line mode, that is.

**Comment by wickedest** [comment]
@JC3, I just added support for comparing arrays instead of strings in [2.1.0](https://github.com/wickedest/myers-diff/releases/tag/v2.1.0).

**Comment by JC3** [comment]
> @JC3, I just added support for comparing arrays instead of strings in [2.1.0](https://github.com/wickedest/myers-diff/releases/tag/v2.1.0).

Sweet! Thanks for this package; it's very easy to use and works well.

**Comment by JC3** [comment]
I updated the docs if you want. Thanks again!
